export const APP = {
    LOAD: 'APP_LOAD'  
}

export const MOVIES = {
    LOAD: 'MOVIES_LOAD',
    LOAD_SUCCESS: 'MOVIES_LOAD_SUCCESS', 
    LOAD_FAIL: 'MOVIES_LOAD_FAIL',    
}

export const DETAILS = {
    LOAD: 'DETAILS_LOAD',
    LOAD_SUCCESS: 'DETAILS_LOAD_SUCCESS', 
    LOAD_FAIL: 'DETAILS_LOAD_FAIL',    
}

export const REVIEWS = {
    LOAD: 'REVIEWS_LOAD',
    LOAD_SUCCESS: 'REVIEWS_LOAD_SUCCESS', 
    LOAD_FAIL: 'REVIEWS_LOAD_FAIL',    
}